<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="flask_tests.AppTestCase-20220307124429" tests="2" file="flask_tests.py" time="0.007" timestamp="2022-03-07T12:44:31" failures="0" errors="1" skipped="0">
	<testcase classname="flask_tests.AppTestCase" name="test" time="0.002" timestamp="2022-03-07T12:44:31"/>
	<testcase classname="flask_tests.AppTestCase" name="test_home" time="0.005" timestamp="2022-03-07T12:44:31">
		<error type="NameError" message="name 'loggings' is not defined"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\johnny\desktop\everything\school\cs 4800 software engineering\bronco-mates\src\unittest\python\flask_tests.py", line 28, in test_home
    loggings.warning("status code" % status)
NameError: name 'loggings' is not defined
]]></error>
	</testcase>
</testsuite>
