<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20220228090547" tests="1" file="unittest/loader.py" time="0.003" timestamp="2022-02-28T09:05:48" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="start_tests" time="0.003" timestamp="2022-02-28T09:05:48">
		<error type="ImportError" message="Failed to import test module: start_tests
Traceback (most recent call last):
  File &quot;C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\johnny\desktop\everything\school\cs 4800 software engineering\bronco-mates\src\unittest\python\start_tests.py&quot;, line 4, in &lt;module&gt;
    from app import start
ModuleNotFoundError: No module named 'app'
"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: start_tests
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\johnny\desktop\everything\school\cs 4800 software engineering\bronco-mates\src\unittest\python\start_tests.py", line 4, in <module>
    from app import start
ModuleNotFoundError: No module named 'app'

]]></error>
	</testcase>
</testsuite>
